
backend:
  name: git-gateway
  branch: main

media_folder: "uploads"
public_folder: "/uploads"

collections:
  - name: "blog_en"
    label: "Blog (English)"
    folder: "content/blog_en"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Title", name: "title", widget: "string"}
      - {label: "Date", name: "date", widget: "datetime"}
      - {label: "Body", name: "body", widget: "markdown"}

  - name: "blog_om"
    label: "Oduu (Afaan Oromo)"
    folder: "content/blog_om"
    create: true
    slug: "{{slug}}"
    fields:
      - {label: "Mata-duree", name: "title", widget: "string"}
      - {label: "Guyyaa", name: "date", widget: "datetime"}
      - {label: "Qabiyyee", name: "body", widget: "markdown"}
